/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AutoForm: typeof import('./components/AutoForm/AutoForm.vue')['default']
    BoolValue: typeof import('./components/AutoForm/BoolValue.vue')['default']
    ChoiceBuilder: typeof import('./components/AutoForm/ChoiceBuilder.vue')['default']
    copy: typeof import('./components/AutoForm/FormBuilder copy.vue')['default']
    FormBuilder: typeof import('./components/AutoForm/FormBuilder.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IntegerFormValue: typeof import('./components/AutoForm/IntegerFormValue.vue')['default']
    NumberFormValue: typeof import('./components/AutoForm/NumberFormValue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StringFormValue: typeof import('./components/AutoForm/StringFormValue.vue')['default']
    TextFormValue: typeof import('./components/AutoForm/TextFormValue.vue')['default']
  }
}
